package com.runie.assets;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.runie.creatures.CreatureDefinition;
import com.runie.creatures.CreatureRegistry;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Set;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * The bundled assets manifest ({@code com/runie/assets_manifest.json},
 * generated by tools/gen_manifest.py) is the contract between the approved
 * sprite set and the §5.1 resource tree that tools/fetch_assets.sh installs
 * into. This test locks: full 42 x 3 x 2 coverage, path-convention agreement
 * with AssetLoader, and that EVERY manifest target resolves on the classpath
 * right now (real art or marked placeholder — the build must never ship a
 * blank grid slot).
 */
public class AssetManifestTest
{
	private static final String MANIFEST_PATH = "/com/runie/assets_manifest.json";

	private CreatureRegistry registry;
	private JsonArray entries;

	@Before
	public void setUp() throws Exception
	{
		registry = new CreatureRegistry(new Gson());
		registry.load();
		try (InputStream in = AssetManifestTest.class.getResourceAsStream(MANIFEST_PATH))
		{
			assertNotNull("bundled assets manifest missing: " + MANIFEST_PATH, in);
			try (Reader r = new InputStreamReader(in, StandardCharsets.UTF_8))
			{
				JsonObject manifest = new Gson().fromJson(r, JsonObject.class);
				entries = manifest.getAsJsonArray("entries");
			}
		}
	}

	@Test
	public void coversFullRosterTimesStagesTimesStyles()
	{
		assertEquals(40 * 3 * 2, entries.size());
		Set<String> seen = new HashSet<>();
		Set<String> imageIds = new HashSet<>();
		Set<String> urls = new HashSet<>();
		for (int i = 0; i < entries.size(); i++)
		{
			JsonObject e = entries.get(i).getAsJsonObject();
			String cid = e.get("creatureId").getAsString();
			assertTrue("manifest creature not in registry: " + cid, registry.contains(cid));
			int stage = e.get("stage").getAsInt();
			assertTrue("bad stage " + stage, stage >= 1 && stage <= 3);
			String style = e.get("style").getAsString();
			assertTrue("bad style " + style,
				style.equals(ArtStyle.KAWAII.getFolderToken()) || style.equals(ArtStyle.PIXEL.getFolderToken()));
			assertTrue("duplicate cell", seen.add(cid + '|' + style + '|' + stage));
			assertTrue("duplicate imageId", imageIds.add(e.get("imageId").getAsString()));
			assertTrue("duplicate url", urls.add(e.get("url").getAsString()));
		}
		// every registry line appears with all 6 cells
		for (CreatureDefinition def : registry.all())
		{
			for (String style : new String[]{"kawaii", "pixel"})
			{
				for (int stage = 1; stage <= 3; stage++)
				{
					assertTrue("missing manifest cell: " + def.getId() + '/' + style + "/stage" + stage,
						seen.contains(def.getId() + '|' + style + '|' + stage));
				}
			}
		}
	}

	@Test
	public void resourcePathsFollowTheSection5Convention()
	{
		for (int i = 0; i < entries.size(); i++)
		{
			JsonObject e = entries.get(i).getAsJsonObject();
			ArtStyle style = "pixel".equals(e.get("style").getAsString()) ? ArtStyle.PIXEL : ArtStyle.KAWAII;
			String expected = AssetLoader.framePath(
				e.get("creatureId").getAsString(), style, e.get("stage").getAsInt(), "idle", 0);
			assertEquals(expected, "/" + e.get("resourcePath").getAsString());
		}
	}

	@Test
	public void downloadIndexCoversWholeRosterIdleArt()
	{
		// Art no longer ships in the jar (10 MB Plugin Hub limit) — it streams from
		// the repo's assets branch via RunieAssetService. Lock that the bundled
		// download index (art_index.json) covers an idle sheet for EVERY roster
		// line × style × stage, so nothing is left un-fetchable.
		JsonObject idx;
		try (InputStream in = AssetManifestTest.class.getResourceAsStream("/com/runie/art_index.json");
			Reader r = new InputStreamReader(in, StandardCharsets.UTF_8))
		{
			assertNotNull("art_index.json missing from resources", in);
			idx = new Gson().fromJson(r, JsonObject.class);
		}
		catch (Exception ex)
		{
			throw new AssertionError("failed reading art index", ex);
		}

		String base = idx.get("base").getAsString();
		assertTrue("index base must be an https github URL: " + base,
			base.startsWith("https://") && base.contains("github"));
		assertTrue("index needs a version", idx.get("version").getAsInt() >= 1);
		JsonArray files = idx.getAsJsonArray("files");
		assertTrue("index must list art files", files.size() > 0);

		Set<String> paths = new HashSet<>();
		for (int i = 0; i < files.size(); i++)
		{
			paths.add(files.get(i).getAsString());
		}

		for (CreatureDefinition def : registry.all())
		{
			for (String style : new String[]{"kawaii", "pixel"})
			{
				for (int stage = 1; stage <= 3; stage++)
				{
					String prefix = "com/runie/creatures/" + def.getId()
						+ "/art/" + style + "/stage" + stage + "/idle/idle.";
					boolean found = paths.stream().anyMatch(p -> p.startsWith(prefix));
					assertTrue("download index missing idle art: " + prefix, found);
				}
			}
		}
	}

	@Test
	public void urlsAreAbsoluteHttpsPngs()
	{
		for (int i = 0; i < entries.size(); i++)
		{
			JsonObject e = entries.get(i).getAsJsonObject();
			String url = e.get("url").getAsString();
			assertTrue(url, url.startsWith("https://") && url.endsWith(".png"));
			assertTrue(url, url.contains(e.get("imageId").getAsString()));
		}
	}
}
